#pragma once

#include "dhkClass.h"
#include <unordered_map>
#include <string>

using namespace std;

class dhkClassLibrary410
{
public:
	dhkClassLibrary410(void);
	~dhkClassLibrary410(void);

	dhkClass* getClass(const char*);

private:

	static const dhkClassMember hkRootLevelContainerNamedVariantMembers[];
	static const dhkClassMember hkRootLevelContainerMembers[];
	static const dhkClassMember hkVariantMembers[];
	static const dhkClassMember hkArrayMembers[];
	static const dhkClassMember hkSmallArrayMembers[];
	static const dhkClassMember hkAnimationContainerMembers[];
	static const dhkClassMember hkReferencedObjectMembers[];
	static const dhkClassMember hkSkeletalAnimationMembers[];
	static const char* hkSkeletalAnimationParents[];
	static const dhkClassMember hkWaveletSkeletalAnimationMembers[];
	static const char* hkWaveletSkeletalAnimationParents[];
	static const dhkClassMember hkWaveletSkeletalAnimationQuantizationFormatMembers[];
	static const dhkClassMember hkDefaultAnimatedReferenceFrameMembers[];
	static const char* hkDefaultAnimatedReferenceFrameMembersParents[];
	static const dhkClassMember hkAnnotationTrackMembers[];
	static const dhkClassMember hkAnnotationTrackAnnotationMembers[];
	static const dhkClassMember hkDeltaCompressedSkeletalAnimationMembers[];
	static const char* hkDeltaCompressedSkeletalAnimationParents[];
	static const dhkClassMember hkAnimationBindingMembers[];
	static const dhkClassMember hkxSceneMembers[];
	static const dhkClassMember hkSkeletonMembers[];
	static const dhkClassMember hkQsTransformMembers[];
	static const dhkClassMember hkBoneMembers[];
	static const dhkClassMember hkPhysicsDataMembers[];
	static const char* hkPhysicsDataParents[];
	static const dhkClassMember hkPhysicsSystemMembers[];
	static const char* hkPhysicsSystemParents[];
	static const dhkClassMember hkCdBodyMembers[];
	static const dhkClassMember hkBroadPhaseHandleMembers[];
	static const dhkClassMember hkTypedBroadPhaseHandleMembers[];
	static const char* hkTypedBroadPhaseHandleParents[];
	static const char* hkCollidableParents[];
	static const dhkClassMember hkCollidableMembers[];
	static const dhkClassMember hkLinkedCollidableMembers[];
	static const char* hkLinkedCollidableParents[];
	static const dhkClassMember hkMultiThreadLockMembers[];
	static const dhkClassMember hkPropertyValueMembers[];
	static const dhkClassMember hkPropertyMembers[];
	static const dhkClassMember hkMaterialMembers[];
	static const dhkClassMember hkWorldObjectMembers[];
	static const char* hkWorldObjectParents[];
	static const dhkClassMember hkTransformMembers[];
	static const dhkClassMember hkSweptTransformMembers[];
	static const dhkClassMember hkMotionStateMembers[];
	static const dhkClassMember hkMotionMembers[];
	static const char* hkMotionParents[];
	static const dhkClassMember hkKeyframedRigidMotionMembers[];
	static const char* hkKeyframedRigidMotionParents[];
	static const char* hkMaxSizeMotionParents[];
	static const dhkClassMember hkEntitySpuCollisionCallbackMembers[];
	static const char* hkEntityParents[];
	static const dhkClassMember hkEntityMembers[];
	static const char* hkRigidBodyParents[];
	static const char* hkShapeParents[];
	static const dhkClassMember hkShapeMembers[];
	static const char* hkSphereRepShapeParents[];
	static const dhkClassMember hkConvexShapeMembers[];
	static const char* hkConvexShapeParents[];
	static const dhkClassMember hkCapsuleShapeMembers[];
	static const char* hkCapsuleShapeParents[];
	static const dhkClassMember hkConstraintDataMembers[];
	static const char* hkConstraintDataParents[];
	static const dhkClassMember hkConstraintAtomMembers[];
	static const dhkClassMember hkSetLocalTransformsConstraintAtomMembers[];
	static const char* hkSetLocalTransformsConstraintAtomParents[];
	static const dhkClassMember hkRagdollMotorConstraintAtomMembers[];
	static const char* hkRagdollMotorConstraintAtomParents[];
	static const dhkClassMember hkAngFrictionConstraintAtomMembers[];
	static const char* hkAngFrictionConstraintAtomParents[];
	static const dhkClassMember hkTwistLimitConstraintAtomMembers[];
	static const char* hkTwistLimitConstraintAtomParents[];
	static const dhkClassMember hkConeLimitConstraintAtomMembers[];
	static const char* hkConeLimitConstraintAtomParents[];
	static const char* hkBallSocketConstraintAtomParents[];
	static const dhkClassMember hkRagdollConstraintDataAtomsMembers[];
	static const dhkClassMember hkRagdollConstraintDataMembers[];
	static const char* hkRagdollConstraintDataParents[];
	static const dhkClassMember hkConstraintInstanceMembers[];
	static const char* hkConstraintInstanceParents[];
	static const dhkClassMember hkRagdollInstanceMembers[];
	static const char* hkRagdollInstanceParents[];
	static const dhkClassMember hkSkeletonMapperDataSimpleMappingMembers[];
	static const dhkClassMember hkSkeletonMapperDataChainMappingMembers[];
	static const dhkClassMember hkSkeletonMapperDataMembers[];
	static const dhkClassMember hkSkeletonMapperMembers[];
	static const char* hkSkeletonMapperParents[];
	static const dhkClassMember hkAngMotorConstraintAtomMembers[];
	static const char* hkAngMotorConstraintAtomParents[];
	static const dhkClassMember hkAngLimitConstraintAtomMembers[];
	static const char* hkAngLimitConstraintAtomParents[];
	static const dhkClassMember hk2dAngConstraintAtomMembers[];
	static const char* hk2dAngConstraintAtomParents[];
	static const dhkClassMember hkLimitedHingeConstraintDataAtomsMembers[];
	static const dhkClassMember hkLimitedHingeConstraintDataMembers[];
	static const char* hkLimitedHingeConstraintDataParents[];
	static const dhkClassMember hkConstraintMotorMembers[];
	static const char* hkConstraintMotorParents[];
	static const dhkClassMember hkMaxSizeConstraintMotorMembers[];
	static const char* hkMaxSizeConstraintMotorParents[];
	static const dhkClassMember hkLimitedForceConstraintMotorMembers[];
	static const char* hkLimitedForceConstraintMotorParents[];
	static const dhkClassMember hkPositionConstraintMotorMembers[];
	static const char* hkPositionConstraintMotorParents[];
	static const dhkClassMember hkConvexVerticesShapeFourVectorsMembers[];
	static const dhkClassMember hkConvexVerticesShapeMembers[];
	static const char* hkConvexVerticesShapeParents[];
	static const dhkClassMember hkSingleShapeContainerMembers[];
	static const char* hkSingleShapeContainerParents[];
	static const dhkClassMember hkConvexTranslateShapeMembers[];
	static const char* hkConvexTranslateShapeParents[];
	static const dhkClassMember hkBoxShapeMembers[];
	static const char* hkBoxShapeParents[];
	//static const dhkClassMember hkSphereShapeMembers[];
	static const char* hkSphereShapeParents[];
	static const dhkClassMember hkCylinderShapeMembers[];
	static const char* hkCylinderShapeParents[];
	static const char* hkEntityDeactivatorParents[];
	static const char* hkRigidBodyDeactivatorParents[];
	static const dhkClassMember hkSpatialRigidBodyDeactivatorMembers[];
	static const char* hkSpatialRigidBodyDeactivatorParents[];
	static const dhkClassMember hkSpatialRigidBodyDeactivatorSampleMembers[];
	static const dhkClassMember hkxAttributeGroupMembers[];
	static const dhkClassMember hkxAttributeMembers[];
	static const dhkClassMember hkxNodeMembers[];
	static const dhkClassMember hkxAnimatedFloatMembers[];
	static const dhkClassMember hkxSparselyAnimatedStringMembers[];
	static const dhkClassMember hkxSparselyAnimatedBoolMembers[];
	static const dhkClassMember hkxSparselyAnimatedIntMembers[];
	static const dhkClassMember hkxMeshMembers[];
	static const dhkClassMember hkxMeshSectionMembers[];
	static const char* hkxMeshUserChannelInfoParents[];
	static const dhkClassMember hkxVertexBufferMembers[];
	static const dhkClassMember hkxVertexFormatMembers[];
	static const dhkClassMember hkxIndexBufferMembers[];
	static const dhkClassMember hkxMaterialMembers[];
	static const dhkClassMember hkxTextureFileMembers[];
	static const dhkClassMember hkxTextureInplaceMembers[];
	static const dhkClassMember hkxNodeAnnotationDataMembers[];
	static const dhkClassMember hkClassMembers[];
	static const dhkClassMember hkClassEnumMembers[];
	static const dhkClassMember hkClassEnumItemMembers[];
	static const dhkClassMember hkClassMemberMembers[];
	static const dhkClassMember hkxMaterialTextureStageMembers[];
	static const dhkClassMember hkMoppBvTreeShapeMembers[];
	static const char* hkMoppBvTreeShapeParents[];
	static const dhkClassMember hkBvTreeShapeMembers[];
	static const char* hkBvTreeShapeParents[];
	static const dhkClassMember hkMoppCodeMembers[];
	static const char* hkMoppCodeParents[];
	static const dhkClassMember hkMoppCodeCodeInfoMembers[];
	static const dhkClassMember hkShapeCollectionMembers[];
	static const char* hkShapeCollectionParents[];
	static const dhkClassMember hkSimpleMeshShapeMembers[];
	static const char* hkSimpleMeshShapeParents[];
	static const dhkClassMember hkSimpleMeshShapeTriangleMembers[];
	static const dhkClassMember hkxVertexP4N4T4B4W4I4Q4Members[];
	static const dhkClassMember hkxVertexP4N4C1T2Members[];
	static const dhkClassMember hkBallAndSocketConstraintDataMembers[];
	static const char* hkBallAndSocketConstraintDataParents[];
	static const dhkClassMember hkBallAndSocketConstraintDataAtomsMembers[];
	static const dhkClassMember hkSetLocalTranslationsConstraintAtomMembers[];
	static const char* hkSetLocalTranslationsConstraintAtomParents[];
	

	unordered_map<string, dhkClass> m_classMap;
};

